added packer and modified webflow accordingly

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -9,10 +9,46 @@ jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        go-version: [ '1.19', '1.20', '1.21.x' ]
     steps:
       - uses: actions/checkout@v4
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
-          go-version: '1.20'
+          go-version: '1.21'
+      # - name: Install dependencies
+      #   run: go get .
+      # - name: Build
+      #   run: go build -v ./...
+      # - name: Test with the Go CLI
+      #   run: go test
+
+      - name: Packer setup
+        uses: hashicorp/setup-packer@main
+        id: setup
+        with:
+          version: latest
+
+      - name: Packer init
+        id: init
+        run: "packer init ./packer.pkr.hcl"
+
+      - name: Packer validation
+        id: validate
+        run: |
+          if ! packer validate ./packer.pkr.hcl ; then
+            echo "Validation failure"
+            exit 1
+          fi
+
+      - name: Packer fmt
+        id: fmt
+        run: |
+          if ! packer fmt -check ./packer.pkr.hcl ; then
+            echo "Formatting failure"
+            exit 1
+          fi
+
       - run: echo "Check successful"
